version: '3'
services:
  fivem:
    image: localhost:9999/fivem:latest
    platform: "x86_64"
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "./:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "2222:22"
    environment:
      LICENSE_KEY: cfxk_Ii9ETwq9XrcNrn31usFs_1evdWq
  mysql:
    image: erryial/fivem-sqlserver
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Erryial123
      MYSQL_USER: user
      MYSQL_PASSWORD: Erryial123
      MYSQL_DATABASE: fivem

